plugins {
	alias(libs.plugins.kotlin.jvm)
	alias(libs.plugins.kotlin.spring)
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.dependency.management)
}

dependencies {
	implementation(project(":common"))
	implementation(project(":database"))
	implementation(project(":spec"))
	implementation(libs.spring.boot.starter)
	implementation(libs.spring.boot.starter.actuator)
	implementation(libs.spring.boot.starter.flyway)
	implementation(libs.spring.boot.starter.jdbc)
	implementation(libs.spring.boot.starter.jooq)
	implementation(libs.spring.boot.starter.webmvc)
	implementation(libs.spring.boot.starter.validation)
	implementation(libs.kotlin.reflect)
	implementation(libs.flyway.database.postgresql)
	implementation(libs.jackson.module.kotlin)
	implementation(libs.jackson.dataformat.xml)
	implementation(libs.maven.artifacts)
	developmentOnly(libs.spring.boot.devtools)
	runtimeOnly(libs.postgresql)
	testImplementation(libs.spring.boot.starter.test)
	testImplementation(libs.spring.boot.starter.actuator.test)
	testImplementation(libs.spring.boot.starter.flyway.test)
	testImplementation(libs.spring.boot.starter.jdbc.test)
	testImplementation(libs.spring.boot.starter.jooq.test)
	testImplementation(libs.spring.boot.starter.webmvc.test)
	testImplementation(libs.spring.boot.testcontainers)
	testImplementation(libs.testcontainers.postgresql)
}
